version: '3'
services:
    web:
        image: dockerhub.singulato.com/singulato/nginx-php:latest
        ports:
            - 80:80
        links:
            - mysql-some
        volumes:
            - ./:/data/www/
            - ./etc/nginx/app.conf:/etc/nginx/conf.d/app.conf
    mysql-some:
        image: mysql:5.6
        ports:
            - 3306:3306
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root123
